### PR TITLE
Fix extra lines in output (issue #156)

### PR DESCRIPTION
**Pull request by Dliv3**
Fixed the issue #156

```bash
$ go run main.go --namespace default
NAME                                                 LIST  CREATE  UPDATE  DELETE
bindings                                                   ✔
cephblockpools.ceph.rook.io                          ✔     ✔       ✔       ✔
cephclients.ceph.rook.io                             ✔     ✔       ✔       ✔
cephclusters.ceph.rook.io                            ✔     ✔       ✔       ✔
cephfilesystemmirrors.ceph.rook.io                   ✔     ✔       ✔       ✔
cephfilesystems.ceph.rook.io                         ✔     ✔       ✔       ✔
cephnfses.ceph.rook.io                               ✔     ✔       ✔       ✔
cephobjectrealms.ceph.rook.io                        ✔     ✔       ✔       ✔
cephobjectstores.ceph.rook.io                        ✔     ✔       ✔       ✔
cephobjectstoreusers.ceph.rook.io                    ✔     ✔       ✔       ✔
cephobjectzonegroups.ceph.rook.io                    ✔     ✔       ✔       ✔
cephobjectzones.ceph.rook.io                         ✔     ✔       ✔       ✔
cephrbdmirrors.ceph.rook.io                          ✔     ✔       ✔       ✔
......
```

### CODE REVIEW

**Comment by GRomR1** [comment]
@corneliusweig would be great to merge this fixes and publish new version.

I have local built it and everything looks fine. No empty lines.

```
❯ ./rakkess --sa "default:test-sa"
NAME                                                          LIST  CREATE  UPDATE  DELETE
alertmanagerconfigs.monitoring.coreos.com                     ✖     ✖       ✖       ✖
alertmanagers.monitoring.coreos.com                           ✖     ✖       ✖       ✖
apiservers.operator.tigera.io                                 ✖     ✖       ✖       ✖
...
```

**Comment by rdeusser** [comment]
@corneliusweig It would be really nice to get this merged whenever you've got some time.

**Comment by Zeratoxx** [comment]
The GitHub account @corneliusweig wasn't active since December last year.. eventually we need a new fork?

**Comment by corneliusweig** [comment]
Apologies for the absence. If anyone wants to step up to shepherd fixes like these, please drop me a message.

**Pull request merged**
